-- Seed councils from CSV data
-- Run after 001_schema.sql
-- Generated from uk_planning_scraper authorities.csv

INSERT INTO councils (name, slug, portal_url, system, region, coverage_source) VALUES
('Aberdeen City Council', 'aberdeen-city-council', 'https://publicaccess.aberdeencity.gov.uk/online-applications/search.do?action=advanced', 'idox', 'scotland', 'pending'),
('Adur and Worthing Councils', 'adur-and-worthing-councils', 'https://planning.adur-worthing.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Allerdale Borough Council', 'allerdale-borough-council', 'https://planning.allerdale.gov.uk/portal/servlets/ApplicationSearchServlet', 'other', 'england', 'pending'),
('Amber Valley Borough Council', 'amber-valley-borough-council', 'https://www.ambervalley.gov.uk/environment-and-planning/planning/development-management/planning-applications/view-a-planning-application.aspx', 'other', 'england', 'pending'),
('Arun District Council', 'arun-district-council', 'https://www.arun.gov.uk/weekly-lists', 'other', 'england', 'pending'),
('Ashfield District Council', 'ashfield-district-council', 'https://www2.ashfield.gov.uk/cfusion/Planning/plan_findfile.cfm', 'other', 'england', 'pending'),
('Ashford Borough Council', 'ashford-borough-council', 'http://planning.ashford.gov.uk/planning/Default.aspx?new=true', 'other', 'england', 'pending'),
('Aylesbury Vale District Council', 'aylesbury-vale-district-council', 'https://publicaccess.aylesburyvaledc.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Babergh District Council', 'babergh-district-council', 'https://planning.baberghmidsuffolk.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Barking and Dagenham LBC', 'barking-and-dagenham-lbc', 'http://paplan.lbbd.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Barnet LBC', 'barnet-lbc', 'https://publicaccess.barnet.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Bedford Borough Council', 'bedford-borough-council', 'http://www.publicaccess.bedford.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Bexley LBC', 'bexley-lbc', 'http://pa.bexley.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Birmingham City Council', 'birmingham-city-council', 'https://eplanning.birmingham.gov.uk/Northgate/PlanningExplorer/GeneralSearch.aspx', 'northgate', 'england', 'pending'),
('Blackpool Council', 'blackpool-council', 'https://idoxpa.blackpool.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Bolton Council', 'bolton-council', 'https://www.planningpa.bolton.gov.uk/online-applications-17/search.do?action=advanced', 'idox', 'england', 'pending'),
('Bracknell Forest Council', 'bracknell-forest-council', 'https://planapp.bracknell-forest.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Bradford MDC', 'bradford-mdc', 'https://planning.bradford.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Brent LBC', 'brent-lbc', 'https://pa.brent.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Brighton and Hove City Council', 'brighton-and-hove-city-council', 'https://planningapps.brighton-hove.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Bristol City Council', 'bristol-city-council', 'https://planningonline.bristol.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Bromley LBC', 'bromley-lbc', 'https://searchapplications.bromley.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Bury MBC', 'bury-mbc', 'https://planning.bury.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Calderdale MBC', 'calderdale-mbc', 'https://portal.calderdale.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Camden LBC', 'camden-lbc', 'https://planningrecords.camden.gov.uk/Northgate/PlanningExplorer/GeneralSearch.aspx', 'northgate', 'england', 'pending'),
('Cardiff Council', 'cardiff-council', 'https://planningonline.cardiff.gov.uk/online-applications/search.do?action=advanced', 'idox', 'wales', 'pending'),
('Cheshire West and Chester Council', 'cheshire-west-and-chester-council', 'https://pa.cheshirewestandchester.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('City of London', 'city-of-london', 'http://www.planning2.cityoflondon.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Croydon LBC', 'croydon-lbc', 'http://publicaccess2.croydon.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Dacorum Borough Council', 'dacorum-borough-council', 'https://planning.dacorum.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Dartford Borough Council', 'dartford-borough-council', 'https://development.dartford.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Derby City Council', 'derby-city-council', 'https://eplanning.derby.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('East Lindsey District Council', 'east-lindsey-district-council', 'https://www.e-lindsey.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Edinburgh City Council', 'edinburgh-city-council', 'https://citydev-portal.edinburgh.gov.uk/idoxpa-web/search.do?action=advanced', 'idox', 'scotland', 'pending'),
('Epping Forest District Council', 'epping-forest-district-council', 'https://eppingforestdc.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Exeter City Council', 'exeter-city-council', 'https://publicaccess.exeter.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Gloucester City Council', 'gloucester-city-council', 'https://planning.gloucester.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Greenwich LBC', 'greenwich-lbc', 'https://planning.royalgreenwich.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Hackney LBC', 'hackney-lbc', 'https://planningapps.hackney.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Hammersmith and Fulham LBC', 'hammersmith-and-fulham-lbc', 'https://public-access.lbhf.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Haringey LBC', 'haringey-lbc', 'https://www.haringey.gov.uk/planning-and-building-control/planning/planning-applications/search-planning-applications', 'other', 'england', 'pending'),
('Harrow LBC', 'harrow-lbc', 'https://www.harrow.gov.uk/planning-building-control/planning-applications/3', 'other', 'england', 'pending'),
('Hertsmere Borough Council', 'hertsmere-borough-council', 'https://www6.hertsmere.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Islington LBC', 'islington-lbc', 'https://planningandbuilding.islington.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Kensington and Chelsea RLBC', 'kensington-and-chelsea-rlbc', 'https://www.rbkc.gov.uk/planning-and-building-control/planning-applications/search-applications', 'other', 'england', 'pending'),
('Kingston upon Thames RLBC', 'kingston-upon-thames-rlbc', 'https://maps.kingston.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Lambeth LBC', 'lambeth-lbc', 'https://planning.lambeth.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Leeds City Council', 'leeds-city-council', 'https://publicaccess.leeds.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Leicester City Council', 'leicester-city-council', 'https://www.leicester.gov.uk/Northgate/PlanningExplorer/GeneralSearch.aspx', 'northgate', 'england', 'pending'),
('Lewisham LBC', 'lewisham-lbc', 'https://planning.lewisham.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Liverpool City Council', 'liverpool-city-council', 'https://planningexplorer.liverpool.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Manchester City Council', 'manchester-city-council', 'https://pa.manchester.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Merton LBC', 'merton-lbc', 'https://planning.merton.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Newcastle City Council', 'newcastle-city-council', 'https://public.newcastle.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Newham LBC', 'newham-lbc', 'https://pa.newham.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Norfolk County Council', 'norfolk-county-council', 'https://planning.norfolk.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Nottingham City Council', 'nottingham-city-council', 'https://planningapplications.nottinghamcity.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Oxford City Council', 'oxford-city-council', 'https://public.oxford.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Plymouth City Council', 'plymouth-city-council', 'https://planning.plymouth.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Redbridge LBC', 'redbridge-lbc', 'https://www.redbridge.gov.uk/planning-and-regeneration/planning-applications/', 'other', 'england', 'pending'),
('Richmond upon Thames RLBC', 'richmond-upon-thames-rlbc', 'https://www.richmond.gov.uk/planning_applications', 'other', 'england', 'pending'),
('Salford City Council', 'salford-city-council', 'https://www.salford.gov.uk/planning-and-building-control/planning-applications/', 'other', 'england', 'pending'),
('Sheffield City Council', 'sheffield-city-council', 'https://planningapps.sheffield.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Solihull MBC', 'solihull-mbc', 'https://publicaccess.solihull.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Southampton City Council', 'southampton-city-council', 'https://planningpublicaccess.southampton.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Southwark LBC', 'southwark-lbc', 'https://planning.southwark.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Stockport MBC', 'stockport-mbc', 'https://www.stockport.gov.uk/planning-applications', 'other', 'england', 'pending'),
('Sunderland City Council', 'sunderland-city-council', 'https://www.sunderland.gov.uk/planning-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Sutton LBC', 'sutton-lbc', 'https://planningregister.sutton.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Swindon Borough Council', 'swindon-borough-council', 'https://pa.swindon.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Tower Hamlets LBC', 'tower-hamlets-lbc', 'https://development.towerhamlets.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Trafford MBC', 'trafford-mbc', 'https://planning.trafford.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Wakefield MDC', 'wakefield-mdc', 'https://www.wakefield.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Waltham Forest LBC', 'waltham-forest-lbc', 'https://www.walthamforest.gov.uk/planning-and-building-control/planning-applications-0', 'other', 'england', 'pending'),
('Wandsworth LBC', 'wandsworth-lbc', 'https://planning2.wandsworth.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Westminster City Council', 'westminster-city-council', 'https://idoxpa.westminster.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Wigan MBC', 'wigan-mbc', 'https://www.wigan.gov.uk/planning-applications', 'other', 'england', 'pending'),
('Wirral MBC', 'wirral-mbc', 'https://www.wirral.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('Wolverhampton City Council', 'wolverhampton-city-council', 'https://www.wolverhampton.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending'),
('York City Council', 'york-city-council', 'https://planningaccess.york.gov.uk/online-applications/search.do?action=advanced', 'idox', 'england', 'pending')
ON CONFLICT (slug) DO NOTHING;
